server:
  port: 8000

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://39.105.133.157/blyx_fs?useUnicode=true&characterEncoding=utf-8
    username: root
    password: yangyang19880124
    # Springboot2.1.2默认引入的mysql版本version是8.0.13，其driver-class-name为com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    database: 0
    host: 39.105.133.157
    password: yangyang19880124
    pool:
      max-active: 200
      max-idle: 10
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 10000


# type-aliases-package批量设置别名作用：就是在mapper.xml文件中直接写类名，不配置就需要写类的全路径名
mybatis:
  type-aliases-package: com.blyx.infrastructure.entity
  mapper-locations: classpath:mapping/*.xml